### ISSUE TITLE
add regex support to action policy

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcorpc-agent-provider#134]
Match that in https://github.com/choria-plugins/action-policy/issues/7

**Comment by ExalDraen** [comment]
You merged https://github.com/choria-io/mcorpc-agent-provider/pull/135 already but I'll add a couple small comments here:

* we should update the docs to mention this new possibility. I'm happy to take that on if you want. 
* maybe we should add a couple more test cases to cover some pathological edge cases like

```
//    # should fail or at least not match empty strings (?)
/*/  # should fail
////  # should match // I guess
```

**Comment by ripienaar** [comment]
doc tweaks would be good thanks for offering @ExalDraen, I added some more checks and validations - not sure `////` makes sense to test for - it's a valid regex but it would never match anything so I guess thats as expected

https://github.com/choria-io/mcorpc-agent-provider/pull/136

**Comment by ExalDraen** [comment]
Sure, the test cases I mentioned were just suggestions off the top of my head, I was just trying to think of some obviously broken examples.

I have added a small PR for some doc updates, and then I think we can close this issue.

**Comment by ripienaar** [comment]
thank you @ExalDraen
