### ISSUE TITLE
Add a generic external agent provider

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcorpc-agent-provider#97]
We need a way to implement agents as external processes. The ruby provider is kind of the general approach but it does it via a shim which starts up old mco, we dont need all that for the generic case.

We should have a thing that:

 * delivers a request to STDIN or temp file of any external process
 * receives reply on STDOUT or temp file of any external process

We kind of do this for ruby, so we can use something similar to:

https://github.com/choria-io/mcorpc-agent-provider/blob/58eedaa63fe933b2830463fc0e6b83f455cb881f/mcorpc/ruby/agent.go#L28-L46

For the request and reply is just https://github.com/choria-io/mcorpc-agent-provider/blob/58eedaa63fe933b2830463fc0e6b83f455cb881f/mcorpc/mcorpc.go#L65-L70

With an accompanying DDL and some kind of logic for where to go look for external process delivered agents we should be able to make it work.

We'll need a few other things:

 * Agent program should respond to `--should-activate` by exiting 0 for yes 1 for no
 * Auditing is done in the wrapper prior to calling the agent/action
 * Authorization will be supported once choria has a authorizer which it doesnt have now

Today this doesnt exist, we'd build a new agent provider plugin that delivers this.

/cc @optiz0r and @vjanelle

**Comment by ripienaar** [comment]
Wondering if `--should-activate` is just too annoying to implement, rather I should have 2 types of JSON messages:

 * A request type 
 * A introspection type that lets the agent reply with if it should be activated

This is easy to extend later with more types of messages and more types of introspection detail should it be needed (but in this case less is more for sure)

**Comment by optiz0r** [comment]
@ripienaar With the ruby mcorpc agent you have a single entrypoint which took agent and action names and was responsible for discovering and loading the corresponding agent. I quite like this model as it minimises the boilerplate to deliver a new agent (which can be an auto-loaded python class with an interface very similar to the ruby agent class). It does mean needing a shim for each language.

In slack you suggested each agent having a `.py` file as an entrypoint. If taking this approach, how do you want to go about mapping an agent to an executable?
- By convention (i.e. in the `mcollective/agent` directory, having a file with the same name as the agent DDL/json file, but with an executable extension like `.py`, which would be ok, but would need a way to handle conflicts, e.g. `foo.py` and `foo.sh`.
- By discovery (e.g. having a shim report back to choria-server on startup the discovered agents)
- By explicit configuration (not a fan of this option, harder to deploy and defies the zero-configuration aims of choria)

If preferring the second route of having a single file entrypoint per agent, there's nothing to stop me having it be a thin wrapper for a library to minimise boilerplate, perhaps something like:

```python mcollective/agent/foo.py
from mco_agent import Agent, action, entrypoint
class Foo(Agent):
  def should_activate(self):
    return True

  @action
  def status(self, request):
    dosomething()

if __name__ == 'main':
  entrypoint()
```

> Authorization will be supported once choria has a authorizer which it doesnt have now

To have authz now, I'd need to reimplement ActionPolicy policy file processing in the external agents? Is handling this within choria server on your roadmap, and if so what's the expected timeline?

> Wondering if --should-activate is just too annoying to implement in the external tools, rather I should have 2 types of JSON messages

No strong preference either way

> The old mcollective action orientated external caller ... used files for comms rather than STDIN/STDOUT

Do you wish to maintain this behaviour for external agents, or switch to using STDIN/STDOUT for messaging and STDERR for logs?
The external agent could return informational and/or logs as extra parameters within the json response object, which the choria server could log and strip before passing the rest of there results back to the caller?

**Comment by ripienaar** [comment]
In future I suggest 1 executable per `agent` for these kinds of external agent.  You'd have `package.ddl`, `package.json`, `package` files - the last being the agent.

The agent would receive JSON requests and send JSON replies.

**Comment by ripienaar** [comment]
I'll probably give the ruby system the ability to read JSON DDLs to forgo the shit ruby ones, but thats a whole different story since JSON ones are even worse to write :P

**Comment by ripienaar** [comment]
Discovering agnets is just `for all *.json in the external agent dir; parse and activate agent`
